apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: common-app
spec:
  selector:
    app: common-app
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
